# Generated by Django 3.1.4 on 2020-12-10 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResourcesDocument',
        ),
    ]
